FROM node:9.5.0

# Override the base log level (info).
ENV NPM_CONFIG_LOGLEVEL warn

WORKDIR /home/app/

RUN apt-get update && apt-get install apt-transport-https
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install yarn --no-install-recommends

RUN npm install -g nodemon

COPY scripts/run.dev.sh /usr/bin/run.dev.sh
RUN chmod +x /usr/bin/run.dev.sh