version: '3'
services:
  mongodb:
    image: mongo:3.4
    ports:
      - "27017:27017"
    command: mongod --smallfiles

  mongoPanel:
    image: mongo-express
    ports:
      - "8081:8081"
    links:
      - mongodb
    env_file:
      - env/mongoPanel.env

  crawlio:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - "./crawlio:/home/app"
    links:
      - mongodb
    command: "run.dev.sh"
    env_file:
      - env/crawlio.env
