rabbitmq:
  image: rabbitmq:3.5.3-management
  ports:
    - "5672:5672"
    - "15672:15672"

mongodb:
  image: mongo:3.0.4
  ports:
    - "27017:27017"
  command: mongod --smallfiles

best-price-api:
  build: ./best-price-api
  ports:
    - "8090:8090"
    - "8091:8091"
  links:
    - rabbitmq
    - mongodb
  environment:
    SPRING_DATA_MONGODB_URI: mongodb://mongodb/userregistration
    SPRING_RABBITMQ_HOST: rabbitmq
    SPRING_APPLICATION_NAME: registration-service
    SPRING_SLEUTH_ENABLED: "true"
    SPRING_SLEUTH_SAMPLER_PERCENTAGE: 1
  
best-price-fe:
  build: ./best-price-fe
  ports:
    - "5000:5000"