version: '3'
services:
  mongodb:
    image: mongo:3.0.4
    ports:
      - "27017:27017"
    command: mongod --smallfiles

  crawlio-front-end:
    build:
      context: ./crawlio/front-end
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - "./crawlio/front-end:/home/app"
    command: "run-app"
    
  crawlio-search:
    build:
      context: ./crawlio/search
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    links:
      - mongodb
    volumes:
      - "./crawlio/search:/home/app"
    command: "run-app"
