version: '3'
services:
  mongodb:
    image: mongo:3.0.4
    ports:
      - "27017:27017"
    command: mongod --smallfiles

  crawlio:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - "./crawlio:/home/app"
    links:
      - mongodb
    command: "run.dev.sh"
